url_shortener/scissors/urls.py
from django.urls import path
from .views import UrlListView, UrlCreateView, UrlRedirectView, UrlCopyPathView, UrlEditPathView, RedirectPage

app_name = 'scissors'
urlpatterns = [
    path('', UrlListView.as_view(), name='list-url'),
    path('url/', UrlCreateView.as_view(), name='create-url'),
    path('s/<str:path>/', UrlRedirectView.as_view(), name='redirect-url'),
    path('copy/<int:pk>/', UrlCopyPathView.as_view(), name='copy-url'),
    path('<int:pk>/', UrlEditPathView.as_view(), name='edit-url'),
    path('about_us/', RedirectPage.as_view(), name='redirect-page'),


]

url_shortener/url_shortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scissors.urls')),
]

url_shortener/scissors/models.py
from django.db import models


class Url(models.Model):
    original = models.URLField(verbose_name='original path')
    path = models.CharField(
        max_length=50, verbose_name='shortenerd path', unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated_at',)

url_shortener/scissors/forms.py
from django import forms
from .models import Url
from .utils import random_characters


class UrlForm(forms.ModelForm):
    original = forms.URLField(widget=forms.TextInput(
        attrs={'Placeholder': 'example.com/abc/def/ghi'}))
    path = forms.CharField(required=False)

    class Meta:
        model = Url
        fields = ('original', 'path')

    """If the user does not want to enter the path herself, 
    a random 5-letter character will be generated."""

    def clean(self):
        clean_data = super().clean()

        if not clean_data['path']:
            clean_data['path'] = random_characters()

        return clean_data

url_shortener/scissors/views.py
from django.views.generic import list, edit, base, UpdateView
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views import View
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Url
from .forms import UrlForm
import pyperclip


class UrlListView(list.ListView):
    template_name = 'index.html'
    queryset = Url.objects.all()
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UrlForm()
        return context


class UrlCreateView(edit.CreateView):
    form_class = UrlForm
    template_name = 'index.html'

    def get_success_url(self):
        return reverse('scissors:list-url')


class UrlRedirectView(base.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        url = get_object_or_404(Url, path=kwargs['path'])
        return url.original


class UrlCopyPathView(View):
    def get(self, request, pk):
        path = get_object_or_404(Url, pk=pk).path
        pyperclip.copy(f'/s/{path}')
        return HttpResponseRedirect(reverse('scissors:list-url'))


class UrlEditPathView(UpdateView):
    form_class = UrlForm
    template_name = 'index.html'
    queryset = Url.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Url.objects.order_by('-updated_at')[:5]
        context['edit'] = 'edit'
        return context

    def get_success_url(self):
        return reverse('scissors:list-url')


class RedirectPage(View):
    def get(self, request):
        return render(request, 'about_us.html')

url_shortener/scissors/templates/about_us.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Url shortener</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>

<body style="background-color: rgb(197, 201, 204);">
    {% block about %}
    <div class='about-us'>
        <h1>About us:</h1>
        <div style="background-color: rgb(184, 194, 235); height: 300px;"></div>
    </div>
    {% endblock %}

</body>

</html>

url_shortener/scissors/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Url Shortener</title>
    <link rel="stylesheet" href="../static/css/style.css">
</head>

<body>
    <div id='menu'>
        <ul>
            <li><a href="{% url 'scissors:list-url' %}">Home</a></li>
            <li><a href="{% url 'scissors:redirect-page' %}">about us</a></li>
        </ul>
    </div>

    <div id='url-creation'>
        <div>
            {% block url %}
            {% endblock %}
        </div>

        <div>
            {% block list %}
            {% endblock %}
        </div>
        <div>
            {% block edit %}
            {% endblock %}
        </div>
        <div>
            {% block about %}
            {% endblock %}
        </div>
    </div>
    {% block pagination %}
    {% endblock %}
</body>

</html>

url_shortener/scissors/templates/index.html
{% extends 'base.html' %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../static/css/style.css">
    <title>Url shortener</title>
</head>

<body>
    {% block url %}
    <div>
        <form action="{% url 'scissors:create-url' %}" method="post">
            {%csrf_token%}
            {{form.as_p}}
            {% if edit %}
            <!-- editing url -->
            <input style="width: 110px; margin-left: 15px;" type="submit" , value="Edit">
            {% else %}
            <!-- creating url -->
            <input style="width: 110px; margin-left: 15px;" type="submit" , value="Start">
            {% endif %}
        </form>
    </div>
    {% endblock %}

    {% block list %}
    <div>
        <table>
            {% for url in object_list %}
            <tr>
                <td>
                    <!-- copy icon -->
                    <a href="{% url 'scissors:copy-url' url.pk %}"><img src="../static/icons/copy.png"
                            style="margin-right:5px; cursor: pointer; width: 40px;" title="copy path"></a>
                    <!-- edit icon -->
                    <a href="{% url 'scissors:edit-url' url.pk %}"><img src="../static/icons/edit.png"
                            style="cursor:pointer; width: 40px;" title="edit"></a>
                </td>
                <td>/s/{{url.path}}</td>
                <td>{{url.original}}</td>
            </tr>
            {% endfor %}
        </table>

    </div>
    {% endblock %}

    <!-- next & previous button -->
    {% block pagination %}
    {% if not edit %}
    <div class="button">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="previous">&laquo; Previous</a>
        {% endif %}

        <span>
            page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="next">Next &raquo;</a>
        {% endif %}
    </div>
    {% endif %}
    {% endblock %}

</body>

</html>